### ISSUE TITLE
Error: release singed-seastar failed: StatefulSet.apps "singed-seastar" is invalid

### ISSUE THREAD

**Issue by jc1518** [Praqma/ask#3] opened 2019-10-21 11:10 UTC
Hi @hoeghh  I got the following errors when trying to install jira and confluence chart to a minikube cluster. Any ideas?

$helm install ask/jira
Error: release singed-seastar failed: StatefulSet.apps "singed-seastar" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"singed-seastar"}: `selector` does not match template `labels`]

$helm install ask/confluence
Error: release washed-lizard failed: StatefulSet.apps "washed-lizard" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"washed-lizard"}: `selector` does not match template `labels`]

Environment
`clientVersion:
  buildDate: "2019-10-15T23:41:55Z"
  compiler: gc
  gitCommit: c97fe5036ef3df2967d086711e6c0c405941e14b
  gitTreeState: clean
  gitVersion: v1.16.2
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-09-18T14:27:17Z"
  compiler: gc
  gitCommit: 2bd9643cee5b3b3a5ecbd3af49d09018f0773c77
  gitTreeState: clean
  gitVersion: v1.16.0
  goVersion: go1.12.9
  major: "1"
  minor: "16"
  platform: linux/amd64`

$helm ls
`NAME          	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	NAMESPACE
donating-joey 	1       	Mon Oct 21 21:42:04 2019	DEPLOYED	jenkins-1.7.8   	lts        	default  
singed-seastar	1       	Mon Oct 21 22:01:34 2019	FAILED  	jira-1.0.0      	           	default  
washed-lizard 	1       	Mon Oct 21 22:05:10 2019	FAILED  	confluence-1.0.0	           	default  `

**Comment by michaelvl** [comment] 2019-10-21 18:36
This is caused by the statefulsets missing a 'selector' property, which have become required in later API version. This is fixed by commit a5c5a15 and chart version 1.0.1.

**Comment by michaelvl** [comment] 2019-10-21 18:39
Similar issue solved in Jira chart by commit 5626b6f, chart version 1.0.1

**Comment by michaelvl** [comment] 2019-10-21 18:41
Similar issue solved in BitBucket chart by commit e1059fd, chart version 1.0.1

**Comment by jc1518** [comment] 2019-10-21 22:01
Thanks @MichaelVL for the quick fix. I have tested and verified.

**Closed as completed** 2019-10-21 22:01 UTC
